name: Build OpenWrt for S905X

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build OpenWrt for S905X
        uses: ophub/amlogic-s9xxx-openwrt@main
        with:
          openwrt_path: https://downloads.openwrt.org/releases/24.10.0/targets/armvirt/64/openwrt-24.10.0-armvirt-64-generic-rootfs.tar.gz
          openwrt_board: s905x
          openwrt_kernel: 6.1.y
          kernel_usage: stable
          auto_kernel: true
          openwrt_size: 256/1024
          builder_name: brixzen

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-24.10.0-s905x-hg680p
          path: out/*.img.gz
